name: Docker Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - none

  push:
    branches:
      - main
      - dev
    paths:
      - 'bfportal/**'


jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  production-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bfportal

    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1

      - name: Build image
        run: docker build . --file Dockerfile --tag $BRANCH_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$BRANCH_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $BRANCH_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
